### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by maxcom99** [kreso-t/cncjs-kt-ext#14]
pi@raspberrypi:~/cncjs-kt-ext $ npm install
npm WARN cncjs-kt-ext@1.0.0 No repository field.

added 226 packages in 11.663s
pi@raspberrypi:~/cncjs-kt-ext $ node . --port /dev/ttyACM0
Connected to ws://localhost:8000?token=XXXXX
/home/pi/cncjs-kt-ext/autolevel.js:21
    socket.on('gcode:load', (file, gc) => {
           ^

TypeError: Cannot read property 'on' of undefined
    at new Autolevel (/home/pi/cncjs-kt-ext/autolevel.js:21:12)
    at callback (/home/pi/cncjs-kt-ext/index.js:147:19)
    at Socket.<anonymous> (/home/pi/cncjs-kt-ext/index.js:142:3)
    at Socket.Emitter.emit (/home/pi/cncjs-kt-ext/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/home/pi/cncjs-kt-ext/node_modules/socket.io-client/lib/socket.js:278:10)
    at Socket.onpacket (/home/pi/cncjs-kt-ext/node_modules/socket.io-client/lib/socket.js:236:12)
    at Manager.<anonymous> (/home/pi/cncjs-kt-ext/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/pi/cncjs-kt-ext/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/home/pi/cncjs-kt-ext/node_modules/socket.io-client/lib/manager.js:345:8)
    at Decoder.<anonymous> (/home/pi/cncjs-kt-ext/node_modules/component-bind/index.js:21:15)

pi@raspberrypi:~/cncjs-kt-ext $ node -v
v8.11.1

Any ideas? cncjs is up and running

**Comment by maxcom99** [comment]
This is still a bug I believe but for those searching, I had to read the values out of ~/.cncrc

node . --id 'user_id_guid' --name 'user_name' --secret 'secret_token' --port '/dev/ttyAMA0' --baudrate 115200 --socket-address 'localhost' --socket-port 8000

obviously modify the id name and secret values from .cncrc and then the rest of the values depending on your setup.
